remove docker hub action

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -4,7 +4,7 @@ on:
   workflow_dispatch:
   #push:
   #  branches: [ "main" ]
-    
+
 env:
   UBUNTU_VERSION: 22.04
   BUILDX_NO_DEFAULT_ATTESTATIONS: 1
@@ -16,10 +16,14 @@ jobs:
       fail-fast: false
       matrix:
         build:
-          - {latest: "false", comfyui: "v0.2.7", python: "3.10", pytorch: "2.5.1"}
+          - {
+              latest: "false",
+              comfyui: "v0.2.7",
+              python: "3.10",
+              pytorch: "2.5.1",
+            }
     steps:
-      -
-        name: Free Space
+      - name: Free Space
         run: |
           df -h
           sudo rm -rf /usr/share/dotnet
@@ -29,56 +33,44 @@ jobs:
           sudo rm -rf /usr/local/lib/android
           sudo rm -rf "$AGENT_TOOLSDIRECTORY"
           df -h
-      -
-        name: Env Setter
+      - name: Env Setter
         run: |
           REPO=${GITHUB_REPOSITORY,,}
           echo "REPO_NAMESPACE=${REPO%%/*}" >> ${GITHUB_ENV}
           echo "REPO_NAME=${REPO#*/}" >> ${GITHUB_ENV}
-      -
-        name: Checkout
+      - name: Checkout
         uses: actions/checkout@v3
-      -
-        name: Permissions fixes
+      - name: Permissions fixes
         run: |
           target="${HOME}/work/${{ env.REPO_NAME }}/${{ env.REPO_NAME }}/build/COPY*"
           chmod -R ug+rwX ${target}
-      -
-        name: Login to DockerHub
-        uses: docker/login-action@v3
-        with:
-          username: ${{ vars.DOCKERHUB_USER }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-      -
-        name: Login to GitHub Container Registry
+      - name: Login to GitHub Container Registry
         uses: docker/login-action@v3
         with:
           registry: ghcr.io
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
-      -
-        name: Set tags
+      - name: Set tags
         run: |
-            img_path_ghcr="ghcr.io/${{ env.REPO_NAMESPACE }}/${{ env.REPO_NAME }}"
-            if [[ -z '${{ matrix.build.comfyui }}' ]]; then
-                COMFYUI_BUILD_REF="$(curl -s https://api.github.com/repos/comfyanonymous/ComfyUI/tags | jq -r '.[0].name')"
-            else
-                COMFYUI_BUILD_REF="${{ matrix.build.comfyui }}"
-            fi
-            [ -z "$COMFYUI_BUILD_REF" ] && { echo "Error: COMFYUI_BUILD_REF is empty. Exiting script." >&2; exit 1; }
-            echo "COMFYUI_BUILD_REF=${COMFYUI_BUILD_REF}" >> ${GITHUB_ENV}
+          img_path_ghcr="ghcr.io/${{ env.REPO_NAMESPACE }}/${{ env.REPO_NAME }}"
+          if [[ -z '${{ matrix.build.comfyui }}' ]]; then
+              COMFYUI_BUILD_REF="$(curl -s https://api.github.com/repos/comfyanonymous/ComfyUI/tags | jq -r '.[0].name')"
+          else
+              COMFYUI_BUILD_REF="${{ matrix.build.comfyui }}"
+          fi
+          [ -z "$COMFYUI_BUILD_REF" ] && { echo "Error: COMFYUI_BUILD_REF is empty. Exiting script." >&2; exit 1; }
+          echo "COMFYUI_BUILD_REF=${COMFYUI_BUILD_REF}" >> ${GITHUB_ENV}
 
-            base_tag="v2-cpu-${{ env.UBUNTU_VERSION }}"
+          base_tag="v2-cpu-${{ env.UBUNTU_VERSION }}"
 
-            if [[ ${{ matrix.build.latest }} == "true" ]]; then
-                echo "Marking latest"
-                TAGS="${img_path_ghcr}:${base_tag}-${COMFYUI_BUILD_REF}, ${img_path_ghcr}:${base_tag}, ${img_path_ghcr}:latest-cpu"
-            else
-                TAGS="${img_path_ghcr}:${base_tag}-${COMFYUI_BUILD_REF}"
-            fi
-            echo "TAGS=${TAGS}" >> ${GITHUB_ENV}
-      -
-        name: Build and push
+          if [[ ${{ matrix.build.latest }} == "true" ]]; then
+              echo "Marking latest"
+              TAGS="${img_path_ghcr}:${base_tag}-${COMFYUI_BUILD_REF}, ${img_path_ghcr}:${base_tag}, ${img_path_ghcr}:latest-cpu"
+          else
+              TAGS="${img_path_ghcr}:${base_tag}-${COMFYUI_BUILD_REF}"
+          fi
+          echo "TAGS=${TAGS}" >> ${GITHUB_ENV}
+      - name: Build and push
         uses: docker/build-push-action@v4
         with:
           context: build
@@ -91,18 +83,29 @@ jobs:
           # Avoids unknown/unknown architecture and extra metadata
           provenance: false
           tags: ${{ env.TAGS }}
-    
+
   nvidia-base:
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
       matrix:
         build:
-          - {latest: "false", comfyui: "v0.2.7", python: "3.10", pytorch: "2.5.1", cuda: "12.1.1-base"}
-          - {latest: "false", comfyui: "v0.2.7", python: "3.10", pytorch: "2.5.1", cuda: "12.1.1-cudnn8-devel"}
+          - {
+              latest: "false",
+              comfyui: "v0.2.7",
+              python: "3.10",
+              pytorch: "2.5.1",
+              cuda: "12.1.1-base",
+            }
+          - {
+              latest: "false",
+              comfyui: "v0.2.7",
+              python: "3.10",
+              pytorch: "2.5.1",
+              cuda: "12.1.1-cudnn8-devel",
+            }
     steps:
-      -
-        name: Free Space
+      - name: Free Space
         run: |
           df -h
           sudo rm -rf /usr/share/dotnet
@@ -112,38 +115,26 @@ jobs:
           sudo rm -rf /usr/local/lib/android
           sudo rm -rf "$AGENT_TOOLSDIRECTORY"
           df -h
-      -
-        name: Env Setter
+      - name: Env Setter
         run: |
           REPO=${GITHUB_REPOSITORY,,}
           echo "REPO_NAMESPACE=${REPO%%/*}" >> ${GITHUB_ENV}
           echo "REPO_NAME=${REPO#*/}" >> ${GITHUB_ENV}
-      -
-        name: Checkout
+      - name: Checkout
         uses: actions/checkout@v3
-      -
-        name: Permissions fixes
+      - name: Permissions fixes
         run: |
           target="${HOME}/work/${{ env.REPO_NAME }}/${{ env.REPO_NAME }}/build/COPY*"
           chmod -R ug+rwX ${target}
-      -
-        name: Login to DockerHub
-        uses: docker/login-action@v3
-        with:
-          username: ${{ vars.DOCKERHUB_USER }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-      -
-        name: Login to GitHub Container Registry
+      - name: Login to GitHub Container Registry
         uses: docker/login-action@v3
         with:
           registry: ghcr.io
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
-      -
-        name: Set tags
+      - name: Set tags
         run: |
           img_path_ghcr="ghcr.io/${{ env.REPO_NAMESPACE }}/${{ env.REPO_NAME }}"
-          img_path_dhub="${{ vars.DOCKERHUB_USER }}/${{ env.REPO_NAME }}-cuda"
           if [[ -z '${{ matrix.build.comfyui }}' ]]; then
               COMFYUI_BUILD_REF="$(curl -s https://api.github.com/repos/comfyanonymous/ComfyUI/tags | jq -r '.[0].name')"
           else
@@ -158,18 +149,11 @@ jobs:
                 echo "Marking latest"
                 # GHCR.io Tags
                 TAGS="${img_path_ghcr}:${base_tag}-${COMFYUI_BUILD_REF}, ${img_path_ghcr}:${base_tag}, ${img_path_ghcr}:latest, ${img_path_ghcr}:latest-cuda"
-                # Docker.io Tags
-                TAGS="${TAGS}, ${img_path_dhub}:${COMFYUI_BUILD_REF}, ${img_path_dhub}:latest"
             else
-                TAGS="${img_path_ghcr}:${base_tag}-${COMFYUI_BUILD_REF}, ${img_path_dhub}:${COMFYUI_BUILD_REF}"
-            fi
-            # Tag a devel build
-            if [[ ${{ matrix.build.cuda }} = *-devel ]]; then
-                TAGS="${TAGS}, ${img_path_dhub}:${COMFYUI_BUILD_REF}-devel"
+                TAGS="${img_path_ghcr}:${base_tag}-${COMFYUI_BUILD_REF}"
             fi
           echo "TAGS=${TAGS}" >> ${GITHUB_ENV}
-      -
-        name: Build and push
+      - name: Build and push
         uses: docker/build-push-action@v4
         with:
           context: build
@@ -188,10 +172,15 @@ jobs:
       fail-fast: false
       matrix:
         build:
-          - {latest: "false", comfyui: "v0.2.7", python: "3.10", pytorch: "2.3.1", rocm: "6.0-runtime"}
+          - {
+              latest: "false",
+              comfyui: "v0.2.7",
+              python: "3.10",
+              pytorch: "2.3.1",
+              rocm: "6.0-runtime",
+            }
     steps:
-      -
-        name: Free Space
+      - name: Free Space
         run: |
           df -h
           sudo rm -rf /usr/share/dotnet
@@ -201,60 +190,45 @@ jobs:
           sudo rm -rf /usr/local/lib/android
           sudo rm -rf "$AGENT_TOOLSDIRECTORY"
           df -h
-      -
-        name: Env Setter
+      - name: Env Setter
         run: |
           REPO=${GITHUB_REPOSITORY,,}
           echo "REPO_NAMESPACE=${REPO%%/*}" >> ${GITHUB_ENV}
           echo "REPO_NAME=${REPO#*/}" >> ${GITHUB_ENV}
-      -
-        name: Checkout
+      - name: Checkout
         uses: actions/checkout@v3
-      -
-        name: Permissions fixes
+      - name: Permissions fixes
         run: |
           target="${HOME}/work/${{ env.REPO_NAME }}/${{ env.REPO_NAME }}/build/COPY*"
           chmod -R ug+rwX ${target}
-      -
-        name: Login to DockerHub
-        uses: docker/login-action@v3
-        with:
-          username: ${{ vars.DOCKERHUB_USER }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-      -
-        name: Login to GitHub Container Registry
+      - name: Login to GitHub Container Registry
         uses: docker/login-action@v3
         with:
           registry: ghcr.io
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
-      -
-        name: Set tags
+      - name: Set tags
         run: |
-            img_path_ghcr="ghcr.io/${{ env.REPO_NAMESPACE }}/${{ env.REPO_NAME }}"
-            img_path_dhub="${{ vars.DOCKERHUB_USER }}/${{ env.REPO_NAME }}-rocm"
-            if [[ -z '${{ matrix.build.comfyui }}' ]]; then
-                COMFYUI_BUILD_REF="$(curl -s https://api.github.com/repos/comfyanonymous/ComfyUI/tags | jq -r '.[0].name')"
-            else
-                COMFYUI_BUILD_REF="${{ matrix.build.comfyui }}"
-            fi
-            [ -z "$COMFYUI_BUILD_REF" ] && { echo "Error: COMFYUI_BUILD_REF is empty. Exiting script." >&2; exit 1; }
-            echo "COMFYUI_BUILD_REF=${COMFYUI_BUILD_REF}" >> ${GITHUB_ENV}
+          img_path_ghcr="ghcr.io/${{ env.REPO_NAMESPACE }}/${{ env.REPO_NAME }}"
+          if [[ -z '${{ matrix.build.comfyui }}' ]]; then
+              COMFYUI_BUILD_REF="$(curl -s https://api.github.com/repos/comfyanonymous/ComfyUI/tags | jq -r '.[0].name')"
+          else
+              COMFYUI_BUILD_REF="${{ matrix.build.comfyui }}"
+          fi
+          [ -z "$COMFYUI_BUILD_REF" ] && { echo "Error: COMFYUI_BUILD_REF is empty. Exiting script." >&2; exit 1; }
+          echo "COMFYUI_BUILD_REF=${COMFYUI_BUILD_REF}" >> ${GITHUB_ENV}
 
-            base_tag="v2-rocm-${{ matrix.build.rocm }}-${{ env.UBUNTU_VERSION }}"
+          base_tag="v2-rocm-${{ matrix.build.rocm }}-${{ env.UBUNTU_VERSION }}"
 
-            if [[ ${{ matrix.build.latest }} == "true" ]]; then
-                echo "Marking latest"
-                # GHCR.io Tags
-                TAGS="${img_path_ghcr}:${base_tag}-${COMFYUI_BUILD_REF}, ${img_path_ghcr}:${base_tag}, ${img_path_ghcr}:latest-rocm"
-                # Docker.io Tags
-                TAGS="${TAGS}, ${img_path_dhub}:${COMFYUI_BUILD_REF}, ${img_path_dhub}:latest"
-            else
-                TAGS="${img_path_ghcr}:${base_tag}-${COMFYUI_BUILD_REF}, ${img_path_dhub}:${COMFYUI_BUILD_REF}"
-            fi
-            echo "TAGS=${TAGS}" >> ${GITHUB_ENV}
-      -
-        name: Build and push
+          if [[ ${{ matrix.build.latest }} == "true" ]]; then
+              echo "Marking latest"
+              # GHCR.io Tags
+              TAGS="${img_path_ghcr}:${base_tag}-${COMFYUI_BUILD_REF}, ${img_path_ghcr}:${base_tag}, ${img_path_ghcr}:latest-rocm"
+          else
+              TAGS="${img_path_ghcr}:${base_tag}-${COMFYUI_BUILD_REF}"
+          fi
+          echo "TAGS=${TAGS}" >> ${GITHUB_ENV}
+      - name: Build and push
         uses: docker/build-push-action@v4
         with:
           context: build
